# Use postgres/example user/password credentials
version: '3.1'

services:
  db-runners-api:
    image: postgres
    container_name: runners-api
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-runners-api
  db-birthday-bot:
    image: postgres
    container_name: birthday-bot
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-birthday-bot

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
