openapi: 3.0.0
info:
  description: "Свагер сервиса по отображению результатов бегунов"
  version: "1.0.0"
  title: "Swagger Run"
servers:
  - url: https://running-server-bpg.herokuapp.com
tags:
- name: "user"
  description: "Управление пользователями"
paths:
  /user:
    get:
      tags:
      - "user"
      summary: "Получение всех юзеров"
      operationId: "getUsers"
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /user/{id}:
    get:
      tags:
      - "user"
      summary: "Получение юзера по id"
      operationId: "getUserById"
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: '1'
        name:
          type: string
          example: 'Anton'
        surname:
          type: string
          example: 'Rulin'
        birthday:
          type: string
          example: "1999-10-16T00:00:00.000Z"
        gender:
          type: "string"
          enum: 
            - "male"
            - "female"
      required:
        - id
        - name
        - surname
        - birthday
        - gender

