export const TYPES = {
	Application: Symbol.for('Application'),
	PrismaService: Symbol.for('PrismaService'),
	LoggerService: Symbol.for('LoggerService'),
	CompetitionController: Symbol.for('CompetitionController'),
	CompetitionService: Symbol.for('CompetitionService'),
	CompetitionRepository: Symbol.for('CompetitionRepository'),
	StageController: Symbol.for('StageController'),
	StageService: Symbol.for('StageService'),
	StageRepository: Symbol.for('StageRepository'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	UserRepository: Symbol.for('UserRepository'),
	DistanceRepository: Symbol.for('DistanceRepository'),
	DistanceController: Symbol.for('DistanceController'),
	DistanceService: Symbol.for('DistanceService'),
	RaceController: Symbol.for('RaceController'),
	RaceService: Symbol.for('RaceService'),
	FileReaderService: Symbol.for('FileReaderService'),
	StatisticService: Symbol.for('StatisticService'),
	StatisticRepository: Symbol.for('StatisticRepository'),
	StatisticController: Symbol.for('StatisticController'),
};
